from __future__ import annotations
import json
from pathlib import Path
from datetime import datetime, timezone

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / 'reports' / 'institutional-scorecard.json'

def exists(rel: str) -> bool:
    return (ROOT / rel).exists()

def count(glob: str) -> int:
    return len(list(ROOT.glob(glob)))

def main() -> int:
    dimensions = [
        {'name':'category clarity','score':10 if exists('docs/INSTITUTIONAL_CATEGORY_DESIGN.md') else 6},
        {'name':'proof artifacts','score':min(10, count('schemas/*.json'))},
        {'name':'example coverage','score':min(10, count('examples/*.json'))},
        {'name':'operator UX','score':10 if exists('START_HERE.md') and exists('CREATE_REPOSITORY_WEB_UI_GUIDE.md') else 6},
        {'name':'website automation','score':10 if exists('scripts/build_site.py') and exists('scripts/verify_site.py') else 6},
        {'name':'claim boundary','score':10 if exists('CLAIMS.md') and exists('docs/CLAIM_BOUNDARY.md') else 5},
        {'name':'standards registry','score':min(10, count('standards/GOS-*.md'))},
        {'name':'product packaging','score':10 if exists('docs/COMMERCIAL_STRATEGY.md') else 5},
        {'name':'enterprise trust','score':10 if exists('docs/ENTERPRISE_TRUST_PACKAGE.md') else 5},
        {'name':'threat model','score':10 if exists('docs/THREAT_MODEL.md') else 5},
    ]
    avg = round(sum(d['score'] for d in dimensions) / len(dimensions), 2)
    signal = 'institutional-grade repository surface' if avg >= 9 else 'strong repository surface'
    payload = {
        'id':'institutional-scorecard:autogenerated',
        'generated_at_utc':datetime.now(timezone.utc).isoformat(),
        'dimensions':dimensions,
        'average_score':avg,
        'overall_signal':signal,
        'financial_claim_boundary':True,
        'limitations':['score reflects repository completeness only','not a security audit','not a financial outcome claim','not adoption evidence']
    }
    REPORT.parent.mkdir(exist_ok=True)
    REPORT.write_text(json.dumps(payload, indent=2), encoding='utf-8')
    print(json.dumps(payload, indent=2))
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
