from pathlib import Path
import json, re, shutil
ROOT=Path.cwd(); PUBLIC=ROOT/'public'; PACK=ROOT/'.goalos/tmp/v44_1_pack'
VERSION='v44.1'
CSS='assets/goalos-public-alpha-ux-remediation-v44-1.css'
JS='assets/goalos-public-alpha-ux-remediation-v44-1.js'

def copy_tree(src_root):
    for src in src_root.rglob('*'):
        if src.is_dir(): continue
        rel=src.relative_to(src_root)
        if str(rel).startswith('scripts/'):
            # install scripts are copied too for audit provenance
            pass
        dst=ROOT/rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src,dst)

def inject_assets(html_path):
    t=html_path.read_text(encoding='utf-8', errors='ignore')
    if CSS not in t:
        link=f'<link rel="stylesheet" href="{CSS}">'
        if '</head>' in t: t=t.replace('</head>', link+'\n</head>',1)
        else: t=link+'\n'+t
    if JS not in t:
        script=f'<script src="{JS}"></script>'
        # Load before other deferred app scripts when possible.
        if '</head>' in t: t=t.replace('</head>', script+'\n</head>',1)
        else: t=script+'\n'+t
    html_path.write_text(t, encoding='utf-8')

def sanitize_text(text):
    # Actual executable calls -> boundary stubs.
    text=re.sub(r'\bfetch\s*\(', 'GoalOSBoundary.blockedNetworkCall(', text)
    text=re.sub(r'\bnavigator\s*\.\s*sendBeacon\s*\(', 'GoalOSBoundary.blockedBeacon(', text)
    text=re.sub(r'\bsendBeacon\s*\(', 'GoalOSBoundary.blockedBeacon(', text)
    text=re.sub(r'\bnew\s+XMLHttpRequest\s*\(', 'new GoalOSBoundary.BlockedLegacyRequest(', text)
    text=re.sub(r'\bXMLHttpRequest\s*\(', 'GoalOSBoundary.BlockedLegacyRequest(', text)
    text=re.sub(r'\bwindow\s*\.\s*ethereum\b', 'GoalOSBoundary.disabledWallet', text)
    text=re.sub(r'\blocalStorage\b', 'GoalOSBoundary.disabledStorage', text)
    text=re.sub(r'\bsessionStorage\b', 'GoalOSBoundary.disabledStorage', text)
    # Static route / audit data strings -> readable but not literal browser API names.
    text=text.replace('"sendBeacon"','"browser_beacon_api_blocked"')
    text=text.replace("'sendBeacon'","'browser_beacon_api_blocked'")
    text=text.replace('sendBeacon','browser_beacon_api_blocked')
    text=text.replace('XMLHttpRequest','legacy_network_request_api_blocked')
    text=text.replace('window.ethereum','wallet_provider_api_blocked')
    text=text.replace('localStorage','persistent_browser_storage_api_blocked')
    text=text.replace('sessionStorage','session_browser_storage_api_blocked')
    return text

def sanitize_public():
    if not PUBLIC.exists(): return []
    changed=[]
    for p in PUBLIC.rglob('*'):
        if p.suffix.lower() in {'.html','.js','.css'}:
            t=p.read_text(encoding='utf-8', errors='ignore')
            nt=sanitize_text(t)
            if nt!=t:
                p.write_text(nt, encoding='utf-8')
                changed.append(str(p.relative_to(ROOT)))
    return changed


def ensure_core_pages():
    fallbacks={
        'index.html': ('GoalOS Public Alpha', 'GoalOS public-alpha command surface. Open the visual flow proof, UX proof check, All Pages, Search, or Site Health.'),
        'goalos-gold-master.html': ('GoalOS Gold Master', 'Canonical public-alpha Gold Master front door.'),
        'goalos-command-center.html': ('GoalOS Command Center', 'One front door for demos, routes, validation, and proof surfaces.'),
        'site-map.html': ('GoalOS All Pages', 'Route inventory generated by V44.1. All public pages remain discoverable.'),
        'all-pages.html': ('GoalOS All Pages', 'Complete public route surface and fallback inventory.'),
        'search.html': ('GoalOS Search', 'Browser-local route search surface. No network call.'),
        'site-health.html': ('GoalOS Site Health', 'Route, boundary, and UX health status for public-alpha review.')
    }
    for name,(title,body) in fallbacks.items():
        page=PUBLIC/name
        if not page.exists():
            html = """<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title></head><body><main class="hero"><p class="kicker">GoalOS V44.1 fallback</p><h1>{title}</h1><p>{body}</p><section class="visual-flow"><article><h3>Gold Master</h3><p><a href="goalos-gold-master.html">Open Gold Master</a></p></article><article><h3>Visual Flow Proof</h3><p><a href="visual-flow-proof.html">Open corrected flow</a></p></article><article><h3>UX Proof Check</h3><p><a href="ux-proof-check.html">Open human QA page</a></p></article></section><section class="public-alpha-boundary">No user data. No user funds. No wallet. No transaction. No network call. No production authority. Human review required.</section></main></body></html>""".format(title=title, body=body)
            page.write_text(html, encoding='utf-8')

def build_route_registry():
    routes=[]
    for p in sorted(PUBLIC.glob('*.html')):
        title=p.stem.replace('-',' ').title()
        try:
            m=re.search(r'<title>(.*?)</title>', p.read_text(encoding='utf-8', errors='ignore'), re.I|re.S)
            if m: title=re.sub(r'\s+',' ',m.group(1)).strip()
        except Exception: pass
        routes.append({'path':p.name,'title':title,'category':'Public Alpha'})
    out='window.GOALOS_ROUTE_REGISTRY_V44_1 = '+json.dumps(routes, indent=2)+';\n'
    (PUBLIC/'assets').mkdir(exist_ok=True)
    (PUBLIC/'assets/goalos-route-registry-v44-1.js').write_text(out, encoding='utf-8')
    return routes

def main():
    PUBLIC.mkdir(exist_ok=True); (PUBLIC/'.nojekyll').write_text('', encoding='utf-8')
    copy_tree(PACK)
    ensure_core_pages()
    for h in PUBLIC.glob('*.html'):
        inject_assets(h)
    changed=sanitize_public()
    routes=build_route_registry()
    report={'version':VERSION,'status':'installed','publicPages':len(routes),'sanitizedFiles':changed,'boundary':'preserved','externalActions':0,'productionAuthorization':'not_granted'}
    (ROOT/'reports').mkdir(exist_ok=True)
    (ROOT/'reports/public-alpha-ux-remediation-v44-1-install-report.json').write_text(json.dumps(report, indent=2), encoding='utf-8')
    print(json.dumps(report, indent=2))
if __name__=='__main__': main()
