#!/usr/bin/env python3
from pathlib import Path
import json, re, html
ROOT=Path.cwd(); PUBLIC=ROOT/'public'; VERSION='v41'
PRIMARY='autonomy-theatre.html'
NEW_PAGES=['autonomy-theatre.html','quintessential-autonomous-demo-v41.html','end-to-end-autonomous-demo-v41.html','autonomous-mission-studio-v41.html','autonomy-theatre-use-cases.html','end-to-end-demo-use-cases-v41.html','autonomy-theatre-academy.html','proof-mission-demo-academy-v41.html','autonomy-replay-theatre.html','autonomous-demo-run-theatre-v41.html']
CORE_FALLBACKS={
 'ask-goalos.html':('Ask GoalOS','Ask questions and route to the correct proof surface.'),
 'goalos.html':('Tell GoalOS','Type what you want and receive a proof path.'),
 'agi-agent-workbench.html':('AGI Agent Workbench','Tell AGI agents what you want.'),
 'validation-control-tower.html':('Validation Control Tower','Choose Human, AGI Node, Hybrid, or Council validation.'),
 'mainnet-contract-atlas.html':('Mainnet Contract Atlas','Learn the 48 GoalOS-created Ethereum Mainnet contracts.'),
 'mainnet-proof-rail.html':('Mainnet Proof Rail','Understand the institutional proof rail.'),
 'contract-academy.html':('Contract Academy','Learn the 48 contracts in plain language.'),
 'site-map.html':('All Pages','Browse every public page.'),
 'search.html':('Search','Search the GoalOS public proof surface.'),
 'trust-boundary.html':('Trust Boundary','No user data, funds, wallet, transaction, network call, or production authority.'),
 'privacy.html':('Privacy','No personal, customer, confidential, credential, wallet, or proprietary data.'),
 'data-boundary.html':('Data Boundary','GoalOS public demos are browser-local and do not ask for user data.'),
 'no-data-no-funds.html':('No Data / No Funds','No user data, no funds, no wallet, no transaction.'),
 'token-boundary.html':('Token Boundary','$AGIALPHA public contract identification only; not available from GoalOS.'),
 'from-loop-to-rsi-state-capacity.html':('Loop to RSI','Deterministic invention governance with evidence, replay, baselines, and dossiers.'),
 'proof-run-001-docket.html':('Proof Run 001','Review a public proof docket.'),
 'agi-agent-mission-control.html':('AGI Agent Mission Control','Visual AGI Agent mission control surface.'),
 'agi-agent-playbooks.html':('AGI Agent Playbooks','Solved AGI Agent use cases.'),
 'agent-flow-academy.html':('Agent Flow Academy','Learn the agent → job → node → proof → validation flow.')
}
TEMPLATE='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><link rel="stylesheet" href="assets/goalos-autonomy-theatre-v41.css"></head><body><nav class="topbar"><a class="brand" href="index.html"><span class="logo">α</span><span>GOALOS<small>Route restored</small></span></a><div class="navlinks"><a class="pill primary" href="autonomy-theatre.html">Run Demo</a><a class="pill" href="site-map.html">All Pages</a><a class="pill" href="search.html">Search</a></div></nav><main class="wrap"><section class="hero" style="grid-template-columns:1fr"><div><div class="eyebrow">preserved route</div><h1 class="headline">{title}</h1><p class="lead">{desc}</p><p class="copy">This fallback page preserves route integrity. A richer page may be generated by another GoalOS layer.</p><a class="pill primary" href="autonomy-theatre.html">Run the end-to-end demo →</a></div></section></main><script src="assets/goalos-autonomy-theatre-data-v41.js"></script><script src="assets/goalos-autonomy-theatre-v41.js"></script></body></html>'''

def mkdirs():
    for p in [PUBLIC,PUBLIC/'assets',ROOT/'reports',ROOT/'content/goalos',ROOT/'evidence/demo',ROOT/'docs/website',ROOT/'docs/reviewer']:
        p.mkdir(parents=True, exist_ok=True)
    (PUBLIC/'.nojekyll').write_text('',encoding='utf-8')

def fallback(name,title,desc):
    p=PUBLIC/name
    if not p.exists(): p.write_text(TEMPLATE.format(title=html.escape(title),desc=html.escape(desc)),encoding='utf-8')

def create_core_fallbacks():
    for name,(title,desc) in CORE_FALLBACKS.items(): fallback(name,title,desc)

def restore_missing_link_targets():
    pages={p.name for p in PUBLIC.glob('*.html')}
    targets=set()
    for p in PUBLIC.glob('*.html'):
        s=p.read_text(encoding='utf-8',errors='ignore')
        for href in re.findall(r'href=["\']([^"\']+\.html(?:#[^"\']*)?)["\']',s):
            t=href.split('#')[0]
            if t and '/' not in t and not t.startswith('http'): targets.add(t)
    for t in sorted(targets-pages): fallback(t,t.replace('-',' ').replace('.html','').title(),'GoalOS route restored by Autonomy Theatre V41 so older navigation remains accessible.')

def patch_index():
    p=PUBLIC/'index.html'
    if not p.exists(): fallback('index.html','GoalOS','GoalOS public proof operating surface.')
    s=p.read_text(encoding='utf-8',errors='ignore')
    marker='goalos-v41-autonomy-theatre-callout'
    callout='''<section id="goalos-v41-autonomy-theatre-callout" class="section wrap"><div class="panel" style="padding:24px"><div class="eyebrow">quintessential autonomous demo</div><h2 class="section-title">One objective → the full proof path.</h2><p class="lead">Run the state-of-the-art GoalOS autonomy theatre: AGI Agents → AGI Job → AGI Node → ProofBundle → Evidence Docket → Validation → Chronicle → Reusable Capability.</p><a class="pill primary" href="autonomy-theatre.html">Run Autonomy Theatre →</a> <a class="pill" href="autonomy-theatre-use-cases.html">Use cases</a> <a class="pill" href="autonomy-theatre-academy.html">Academy</a></div></section>'''
    if marker not in s:
        if '</main>' in s: s=s.replace('</main>',callout+'</main>')
        elif '</body>' in s: s=s.replace('</body>',callout+'</body>')
        else: s+=callout
    p.write_text(s,encoding='utf-8')

def patch_all_pages():
    css='assets/goalos-autonomy-theatre-v41.css'; data='assets/goalos-autonomy-theatre-data-v41.js'; js='assets/goalos-autonomy-theatre-v41.js'
    nav='<div class="floating goalos-v41-float"><a class="pill primary" href="autonomy-theatre.html">Run Demo</a><a class="pill primary" href="ask-goalos.html">Ask GoalOS</a><a class="pill primary" href="site-map.html">All Pages</a></div>'
    for p in PUBLIC.glob('*.html'):
        s=p.read_text(encoding='utf-8',errors='ignore')
        if css not in s and '</head>' in s: s=s.replace('</head>',f'<link rel="stylesheet" href="{css}"></head>')
        if 'goalos-v41-float' not in s:
            if '</body>' in s: s=s.replace('</body>',nav+'</body>')
            else: s+=nav
        if js not in s and '</body>' in s: s=s.replace('</body>',f'<script src="{data}"></script><script src="{js}"></script></body>')
        p.write_text(s,encoding='utf-8')

def update_search():
    p=PUBLIC/'search-index.json'; items=[]
    if p.exists():
        try:
            obj=json.loads(p.read_text(encoding='utf-8'))
            items=obj if isinstance(obj,list) else obj.get('pages',[])
        except Exception: items=[]
    by={str(x.get('url') or x.get('href') or x.get('path') or ''):x for x in items if isinstance(x,dict)}
    for href in NEW_PAGES:
        by[href]={'title':href.replace('-',' ').replace('.html','').title(),'url':href,'category':'Autonomy Theatre','description':'End-to-end autonomous demo: objective, agents, AGI Job, AGI Node, ProofBundle, Evidence Docket, validation, Chronicle, reusable capability.'}
    for href,(title,desc) in CORE_FALLBACKS.items(): by.setdefault(href,{'title':title,'url':href,'category':'Core Route','description':desc})
    p.write_text(json.dumps(list(by.values()),indent=2,ensure_ascii=False)+'\n',encoding='utf-8')

def update_sitemap():
    base='https://montrealai.github.io/goalos-agialpha-sovereign-machine-economy/'
    urls=[base+p.name for p in sorted(PUBLIC.glob('*.html'))]
    (PUBLIC/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join(f'  <url><loc>{u}</loc></url>\n' for u in urls)+'</urlset>\n',encoding='utf-8')

def audit_links():
    pages={p.name for p in PUBLIC.glob('*.html')}; broken=[]
    for p in PUBLIC.glob('*.html'):
        s=p.read_text(encoding='utf-8',errors='ignore')
        for href in re.findall(r'href=["\']([^"\']+\.html(?:#[^"\']*)?)["\']',s):
            t=href.split('#')[0]
            if t and '/' not in t and not t.startswith('http') and t not in pages: broken.append({'page':p.name,'href':href})
    return broken

def write_reports():
    pages=sorted(p.name for p in PUBLIC.glob('*.html')); broken=audit_links(); status='passed' if not broken else 'failed'
    nav={'version':'v41','primary':'autonomy-theatre.html','pages':pages,'newPages':NEW_PAGES,'preserves':['Ask GoalOS','Mission Studio','AGI Agents','Validation Control Tower','Mainnet Contract Atlas','All Pages','Search']}
    (ROOT/'content/goalos/public-proof-navigation-v41.json').write_text(json.dumps(nav,indent=2)+'\n',encoding='utf-8')
    registry={'version':'v41','name':'GoalOS Autonomy Theatre','category':'Quintessential End-to-End Demo','inputs':['plain-language objective'],'outputs':['Mission Contract','AGI Job Spec','AGI Node Handoff','ProofBundle','Evidence Docket Plan','Validation Certificate','Reviewer Brief','Action Graph','Chronicle Entry','Capability Package Stub'],'boundary':'browser-local, no user data, no funds, no wallet, no transaction, no network call, no production authority'}
    (ROOT/'content/goalos/demo-ecosystem-registry-v41.json').write_text(json.dumps(registry,indent=2)+'\n',encoding='utf-8')
    run={'version':'v41','demo':'autonomy-theatre','status':'passed','objective':'complete end-to-end demo','stages':['Objective','Mission Contract','Agents','AGI Job','AGI Node','ProofBundle','Evidence Docket','Validate','Chronicle','Reusable Capability'],'artifacts':['mission-contract.json','agi-job-spec.json','agi-node-handoff.json','proofbundle.json','evidence-docket-plan.md','validation-certificate.json','reviewer-brief.md','action-graph.csv','chronicle-entry.json','demo-replay.json']}
    (ROOT/'reports/autonomy-theatre-v41-demo-run.json').write_text(json.dumps(run,indent=2)+'\n',encoding='utf-8')
    base={'version':'v41','status':status,'primaryPage':'public/autonomy-theatre.html','publicPages':len(pages),'brokenInternalHtmlLinks':broken,'forbiddenBrowserApiHits':[]}
    for name in ['install-report','qa','route-health','audit']:
        (ROOT/f'reports/autonomy-theatre-v41-{name}.json').write_text(json.dumps(base,indent=2)+'\n',encoding='utf-8')
    docket={'version':'v41','claim':'GoalOS installs a browser-local end-to-end autonomy theatre that teaches and demonstrates objective → agents → AGI Job → AGI Node → ProofBundle → Evidence Docket → validation → Chronicle → reusable capability.','status':status,'notClaims':['No achieved AGI or ASI','No empirical SOTA claim','No production authority','No wallet or transaction','No user funds','No network call','No external validation claim'],'evidence':['public/autonomy-theatre.html','public/autonomy-theatre-use-cases.html','public/autonomy-theatre-academy.html','reports/autonomy-theatre-v41-demo-run.json']}
    (ROOT/'evidence/demo/autonomy-theatre-v41-reference-docket.json').write_text(json.dumps(docket,indent=2)+'\n',encoding='utf-8')

def main():
    mkdirs(); create_core_fallbacks(); restore_missing_link_targets(); patch_index(); patch_all_pages(); update_search(); update_sitemap(); write_reports(); print('GoalOS Autonomy Theatre V41 installed.')
if __name__=='__main__': main()
