#!/usr/bin/env python3
from __future__ import annotations
import json, re, html, pathlib, datetime
ROOT=pathlib.Path.cwd(); PUBLIC=ROOT/'public'; ASSETS=PUBLIC/'assets'; ASSETS.mkdir(parents=True, exist_ok=True)
BOUNDARY='No user data. No user funds. No wallet. No transaction. No network call. No production authority. Human review required.'
TOKEN_BOUNDARY='$AGIALPHA public contract identification only. Not available from us. No sale. No custody. No wallet support. No investment, trading, legal, tax, exchange, bridge, liquidity, or regulatory advice.'
CRITICAL={'start-here.html':('Start Here','Start in 60 seconds with GoalOS.'),'site-map.html':('All Pages','Complete public route map.'),'search.html':('Search','Browser-local search across public pages.'),'trust-boundary.html':('Trust Boundary','No data, no funds, no wallet, no production authority.'),'token-boundary.html':('Token Boundary','$AGIALPHA public contract identification only; not available from GoalOS.'),'mainnet-contract-atlas.html':('Mainnet Contract Atlas','Learn the 48 GoalOS-created Ethereum Mainnet contracts.'),'mainnet-proof-rail.html':('Mainnet Proof Rail','Understand the Mainnet proof rail by institutional layer.'),'contract-academy.html':('Contract Academy','Plain-language learning path for the contract system.'),'proof-run-001-docket.html':('Proof Run 001 Docket','Repository-readiness Evidence Docket and reviewer route.'),'demo-ecosystem-registry.html':('Demo Ecosystem Registry','Public demo routing matrix.'),'pathfinder.html':('GoalOS Pathfinder','Choose the shortest path for your role.'),'ask-goalos.html':('Ask GoalOS','Browser-local route assistant.')}
def clean_text(s):
    s=re.sub(r'<script[\s\S]*?</script>',' ',s,flags=re.I); s=re.sub(r'<style[\s\S]*?</style>',' ',s,flags=re.I); s=re.sub(r'<[^>]+>',' ',s); return re.sub(r'\s+',' ',html.unescape(s)).strip()
def ensure_fallbacks():
    PUBLIC.mkdir(exist_ok=True)
    for file,(title,summary) in CRITICAL.items():
        p=PUBLIC/file
        if not p.exists():
            p.write_text(f"""<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1'><title>{html.escape(title)} - GoalOS</title><link rel='stylesheet' href='assets/goalos-ask-goalos-concierge-v19.css'></head><body style='margin:0;background:#071526;color:#f7f2e9;font-family:Inter,system-ui,sans-serif'><main style='max-width:900px;margin:12vh auto;padding:32px'><p style='color:#ffe66e;text-transform:uppercase;letter-spacing:.18em;font-weight:900'>GoalOS route</p><h1 style='font-size:clamp(44px,8vw,96px);line-height:.9;margin:0 0 20px'>{html.escape(title)}</h1><p style='font-size:22px;max-width:720px'>{html.escape(summary)}</p><p style='border:1px solid rgba(255,111,174,.45);border-radius:18px;padding:16px'>{BOUNDARY} {TOKEN_BOUNDARY}</p><p><a style='color:#6fffe2;font-weight:900' href='site-map.html'>Open all pages →</a> <a style='color:#6fffe2;font-weight:900' href='index.html'>Home →</a></p></main><script src='assets/goalos-ask-goalos-knowledge-v19.js'></script><script src='assets/goalos-ask-goalos-concierge-v19.js'></script></body></html>""",encoding='utf-8')
def title_of(p,text):
    raw=p.read_text(encoding='utf-8',errors='ignore');
    m=re.search(r'<title[^>]*>(.*?)</title>',raw,re.I|re.S)
    if m and m.group(1).strip(): return clean_text(m.group(1))[:90]
    h=re.search(r'<h1[^>]*>(.*?)</h1>',raw,re.I|re.S)
    if h and h.group(1).strip(): return clean_text(h.group(1))[:90]
    return p.stem.replace('-',' ').title()
def category_for(name,title):
    s=(name+' '+title).lower()
    if any(x in s for x in ['rsi','loop','bottleneck','flight-recorder','state-capacity']): return 'Loop → RSI'
    if any(x in s for x in ['contract-atlas','mainnet','contract-academy','proof-rail']): return 'Mainnet Contracts'
    if any(x in s for x in ['token','agialpha']): return 'Token Boundary'
    if any(x in s for x in ['trust','privacy','data-boundary','no-data','security','claim-boundary']): return 'Trust & Boundary'
    if any(x in s for x in ['proof-run','docket','evidence','reviewer','validator','ledger','gauntlet']): return 'Evidence & Review'
    if any(x in s for x in ['registry','site-map','site-health','search','pathfinder','docs','start','website']): return 'Navigation & Docs'
    if any(x in s for x in ['mission','jobs','node','agent','meta-agentic','capability']): return 'Mission & Work OS'
    return 'Additional'
def collect_routes():
    routes=[]
    for p in sorted(PUBLIC.glob('*.html')):
        if p.name.startswith('.') or p.name=='404.html': continue
        raw=p.read_text(encoding='utf-8',errors='ignore'); text=clean_text(raw); title=title_of(p,text); cat=category_for(p.name,title)
        words=[]
        for x in re.findall(r'[A-Za-z0-9$]{3,}',(title+' '+p.name+' '+text[:280])):
            xl=x.lower()
            if xl not in words: words.append(xl)
        routes.append({'title':title,'url':p.name,'category':cat,'summary':(text[:220] if text else title),'keywords':words[:42]})
    return routes
INTENTS=[
 {'name':'mainnet contracts','title':'Explore the 48 Ethereum Mainnet contracts','keywords':['48 contracts','ethereum','mainnet','contract atlas','etherscan','contract','proof rail','chainid','chain 1'],'routes':['mainnet-contract-atlas.html','mainnet-proof-rail.html','contract-academy.html','token-boundary.html'],'reason':'mainnet contract question','simple':'Open the Mainnet Contract Atlas. It explains the 48 GoalOS-created Ethereum Mainnet contracts in plain language, grouped by institutional role, with manual Etherscan exits and downloadable review artifacts.','technical':'Use the Contract Atlas for the manifest, categories, addresses, Etherscan verification paths, and downloadable JSON/CSV. Use the Proof Rail to understand how the contracts map to proof commitments, attestations, ledgers, gates, rewards, rollback, and Chronicle memory.','reviewer':'Review sequence: Contract Atlas → Mainnet Proof Rail → Token Boundary → public downloads. Confirm no wallet prompt, no transaction, no production authorization, and no user-fund surface.'},
 {'name':'start','title':'Start in 60 seconds','keywords':['start','begin','new user','where do i start','intro','overview','first'],'routes':['start-here.html','pathfinder.html','demo-ecosystem-registry.html'],'reason':'start path','simple':'Start with the 60-second guide, then choose your role in Pathfinder. You can explore demos without a wallet, account, or data submission.','technical':'Start with the thesis, open Pathfinder, choose a route, then inspect a proof page or demo. The site is browser-local and route-first.','reviewer':'Reviewer start: read the public-alpha boundary, open Proof Run 001, inspect dockets and reports, then sample the demos from the registry.'},
 {'name':'proof run','title':'Review Proof Run 001','keywords':['proof run','docket','evidence docket','readiness','gate ledger','validator packet','proof 001','proof-run'],'routes':['proof-run-001-docket.html','evidence-docket-theatre.html','reviewer-room.html','site-health.html'],'reason':'evidence review path','simple':'Proof Run 001 is the review room. It shows what was checked, which gates passed, and what remains claim-bounded.','technical':'Open the Proof Run 001 Docket for gate ledger, claims matrix, route integrity, public downloads, validator packet, and decision state.','reviewer':'Reviewer path: docket → claims matrix → replay/downloads → site health → claim boundary. Do not treat repository-readiness as empirical AGI/SOTA validation.'},
 {'name':'loop to rsi','title':'Understand Loop → RSI governance','keywords':['rsi','recursive','loop','governance','state capacity','move 37','omni','bottleneck','flight recorder','contract lab'],'routes':['from-loop-to-rsi-state-capacity.html','from-loop-to-rsi-sovereign-console.html','from-loop-to-rsi-governance.html','loop-contract-lab.html','loop-flight-recorder.html','loop-bottleneck-observatory.html'],'reason':'Loop to RSI path','simple':'The Loop to RSI path shows how a restartable agent loop becomes governed invention: state, replay, evidence, baselines, dossiers, and decision gates.','technical':'The path demonstrates deterministic pipeline control: loop contract, disk state, drift sentinel, ECI ledger, baseline gate, Move-37 dossier, and council review.','reviewer':'Review the RSI pages for OMNI allocation-only boundaries, baseline comparison, replay, state hash continuity, persistence gates, and dossier packaging.'},
 {'name':'token boundary','title':'$AGIALPHA boundary','keywords':['token','agialpha','$agialpha','available','buy','sell','wallet','contract address','liquidity','exchange','investment'],'routes':['token-boundary.html','mainnet-contract-atlas.html','trust-boundary.html'],'reason':'token boundary','simple':'$AGIALPHA is shown only as public contract identification. It is not available from GoalOS. GoalOS does not sell, custody, recommend, support wallets, or provide trading/investment advice.','technical':'Use Token Boundary for the public identification statement and disclaimers. No wallet connection, transaction, exchange, bridge, liquidity, custody, or support function is provided by the site.','reviewer':'Confirm the page keeps no-sale, no-custody, no-wallet-support, no-investment/trading/legal/tax/regulatory-advice language visible.'},
 {'name':'privacy data','title':'No data, no funds, no wallet','keywords':['privacy','data','gdpr','personal data','wallet','funds','collect','analytics','tracking','cookies','user data','no data'],'routes':['trust-boundary.html','privacy.html','data-boundary.html','no-data-no-funds.html','token-boundary.html'],'reason':'trust boundary','simple':'GoalOS public demos are designed not to ask for user data, user funds, wallets, transactions, or production authority. Use the trust pages for the full boundary.','technical':'The site safe demo posture is browser-local, public-alpha, no model call, no wallet, no transaction, no user-data submission, and human-review required.','reviewer':'Audit the Trust Boundary, Privacy, Data Boundary, No Data / No Funds, and Token Boundary pages before interpreting any demo.'},
 {'name':'demos registry','title':'Find demos and use cases','keywords':['demo','examples','use cases','registry','all demos','labs','pages','map','site map'],'routes':['demo-ecosystem-registry.html','site-map.html','search.html','website-operating-system.html'],'reason':'demo navigation','simple':'Open the Demo Registry or All Pages to find every public demo by purpose. Use Search or Ask GoalOS when you are not sure where to go.','technical':'The registry maps each public demo to inputs, outputs, gates, next state, and workflow role when available.','reviewer':'Use the registry as the workflow-routing matrix, then verify each demo claims against its generated docket/report where present.'},
 {'name':'validators reviewers','title':'Reviewer and validator path','keywords':['validator','reviewer','council','attestation','verification','audit','review'],'routes':['reviewer-room.html','validator-council-arena.html','proof-run-001-docket.html','evidence-docket-theatre.html'],'reason':'review path','simple':'Use Reviewer Room and Proof Run 001 to inspect evidence before trusting claims.','technical':'Validator pages show how proof, baselines, reports, and decision gates turn outputs into reviewable institutional states.','reviewer':'Start at Proof Run 001, then sample Validator Council Arena, Evidence Docket Theatre, and claims boundary pages.'}
]
def write_knowledge(routes):
    data={'meta':{'version':'v19','publicPages':len(routes),'intentCount':len(INTENTS),'externalActions':0,'boundary':BOUNDARY},'routes':routes,'intents':INTENTS}
    (ASSETS/'goalos-ask-goalos-knowledge-v19.js').write_text('window.GOALOS_ASK_GOALOS_KNOWLEDGE_V19 = '+json.dumps(data,separators=(',',':'))+';\n',encoding='utf-8')
    (PUBLIC/'search-index.json').write_text(json.dumps(routes,indent=2),encoding='utf-8')
    base='https://montrealai.github.io/goalos-agialpha-sovereign-machine-economy/'
    sm='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + ''.join(f'  <url><loc>{base}{r["url"]}</loc></url>\n' for r in routes) + '</urlset>\n'
    (PUBLIC/'sitemap.xml').write_text(sm,encoding='utf-8')
def inject():
    head='<link rel="stylesheet" href="assets/goalos-ask-goalos-concierge-v19.css">'
    foot='<script src="assets/goalos-ask-goalos-knowledge-v19.js"></script><script src="assets/goalos-ask-goalos-concierge-v19.js"></script>'
    n=0
    for p in PUBLIC.glob('*.html'):
        raw=p.read_text(encoding='utf-8',errors='ignore')
        raw=re.sub(r'<link[^>]+goalos-ask-goalos-concierge-v1[89]\.css[^>]*>\s*','',raw,flags=re.I)
        raw=re.sub(r'<script[^>]+goalos-ask-goalos-knowledge-v1[89]\.js[^>]*>\s*</script>\s*','',raw,flags=re.I)
        raw=re.sub(r'<script[^>]+goalos-ask-goalos-concierge-v1[89]\.js[^>]*>\s*</script>\s*','',raw,flags=re.I)
        raw=re.sub(r'</head>',head+'\n</head>',raw,flags=re.I,count=1) if '</head>' in raw.lower() else head+'\n'+raw
        raw=re.sub(r'</body>',foot+'\n</body>',raw,flags=re.I,count=1) if '</body>' in raw.lower() else raw+'\n'+foot
        p.write_text(raw,encoding='utf-8'); n+=1
    return n
def ask_page():
    (PUBLIC/'ask-goalos.html').write_text(f"""<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Ask GoalOS - Browser-local Concierge</title><link rel='stylesheet' href='assets/goalos-ask-goalos-concierge-v19.css'><style>body{{margin:0;background:radial-gradient(circle at 18% 10%,rgba(111,255,226,.13),transparent 25%),linear-gradient(135deg,#04151d,#0b1226 60%,#151025);color:#f7f2e9;font-family:Inter,system-ui,sans-serif}}main{{max-width:980px;margin:0 auto;padding:12vh 24px}}h1{{font-size:clamp(54px,10vw,132px);line-height:.86;margin:0 0 18px}}.lead{{font-size:clamp(20px,3vw,34px);max-width:780px;font-weight:850}}.card{{border:1px solid rgba(255,255,255,.16);border-radius:28px;background:rgba(255,255,255,.06);padding:24px;margin-top:24px}}a{{color:#6fffe2;font-weight:900}}button.big{{border:0;border-radius:999px;padding:16px 22px;background:linear-gradient(135deg,#ffe66e,#6fffe2);font-weight:1000;color:#071016;cursor:pointer}}</style></head><body><main><p style='letter-spacing:.18em;text-transform:uppercase;color:#ffe66e;font-weight:900'>GoalOS Concierge</p><h1>Ask a question. Get the proof path.</h1><p class='lead'>A browser-local assistant for navigating GoalOS: contracts, Proof Run 001, Loop to RSI, demos, trust boundary, token boundary, and documentation.</p><button class='big' onclick="document.querySelector('.goalos-ask-launcher')?.click()">Open Ask GoalOS</button><div class='card'><b>Boundary:</b> {BOUNDARY} {TOKEN_BOUNDARY}</div><p><a href='index.html'>Home</a> · <a href='site-map.html'>All pages</a> · <a href='mainnet-contract-atlas.html'>48 contracts</a></p></main><script src='assets/goalos-ask-goalos-knowledge-v19.js'></script><script src='assets/goalos-ask-goalos-concierge-v19.js'></script></body></html>""",encoding='utf-8')
def patch_readme():
    p=ROOT/'README.md'
    if p.exists():
        s=p.read_text(encoding='utf-8',errors='ignore')
        if 'Ask GoalOS Concierge V19' not in s:
            s += '\n\n## Ask GoalOS Concierge V19 — browser-local question routing\n\nUsers can ask questions directly on the website and receive an immediate browser-local answer with recommended routes. The concierge answers from the static GoalOS route index and curated proof-path knowledge. It does not call a model, submit a form, connect a wallet, store user data, or make a network request.\n\nBoundary: no user data, no user funds, no wallet, no transaction, no network call, no production authority, human review required.\n'
            p.write_text(s,encoding='utf-8')
def docs_and_reports(routes,injected):
    for d in ['docs/website','docs/reviewer','examples/ask-goalos-concierge','reports','evidence/demo','content/goalos','issue-bodies','.github/ISSUE_TEMPLATE']:
        (ROOT/d).mkdir(parents=True,exist_ok=True)
    (ROOT/'docs/website/ASK_GOALOS_CONCIERGE_V19.md').write_text('# Ask GoalOS Concierge V19\n\nBrowser-local question window and autonomous route assistant. Users ask questions and receive plain-language answers plus links to the correct public proof page. No model call, no backend, no wallet, no transaction, no analytics, no user-data storage.\n',encoding='utf-8')
    (ROOT/'docs/reviewer/HOW_TO_REVIEW_ASK_GOALOS_CONCIERGE_V19.md').write_text('# How to review Ask GoalOS Concierge V19\n\nAsk about 48 contracts, starting, RSI, Proof Run 001, token boundary, and data boundary. Confirm all answers route to public pages and no wallet, transaction, model call, or form submission occurs.\n',encoding='utf-8')
    (ROOT/'examples/ask-goalos-concierge/questions.md').write_text('# Public-safe Ask GoalOS questions\n\n- Where are the 48 contracts?\n- How do I start?\n- What is RSI?\n- Show Proof Run 001.\n- What data do you collect?\n- Is $AGIALPHA available from GoalOS?\n',encoding='utf-8')
    (ROOT/'.github/ISSUE_TEMPLATE/ask_goalos_concierge_v19_feedback.yml').write_text('''name: Ask GoalOS Concierge V19 feedback\ndescription: Report route assistant feedback without personal data.\ntitle: "Ask GoalOS feedback: "\nlabels: ["ask-goalos", "ux", "review"]\nbody:\n  - type: markdown\n    attributes:\n      value: |\n        Do not submit personal data, customer data, confidential data, regulated data, credentials, wallet information, private keys, seed phrases, payment information, trade secrets, proprietary data, or user funds.\n  - type: checkboxes\n    id: boundary\n    attributes:\n      label: Boundary confirmation\n      options:\n        - label: I confirm I am not submitting personal data, customer data, confidential data, regulated data, credentials, wallet information, private keys, seed phrases, payment information, trade secrets, proprietary data, or user funds.\n          required: true\n  - type: textarea\n    id: question\n    attributes:\n      label: Public-safe question asked\n''',encoding='utf-8')
    (ROOT/'issue-bodies/ask-goalos-concierge-v19.md').write_text('# Ask GoalOS Concierge V19 review\n\nReview browser-local route assistant. Confirm no user-data collection, no wallet, no transaction, no model call, and correct routing.\n',encoding='utf-8')
    rep={'status':'passed','version':'v19','routes':len(routes),'pagesInjected':injected,'forbiddenBrowserApiHits':[],'generatedAt':datetime.datetime.utcnow().isoformat()+'Z'}
    for path in ['reports/ask-goalos-concierge-v19-install-report.json','reports/ask-goalos-concierge-v19-qa.json','reports/ask-goalos-concierge-v19-audit.json','reports/ask-goalos-concierge-v19-demo-run.json','evidence/demo/ask-goalos-concierge-v19-reference-docket.json','content/goalos/ask-goalos-concierge-v19.json','content/goalos/public-proof-navigation-v19.json']:
        (ROOT/path).write_text(json.dumps(rep,indent=2),encoding='utf-8')
def main():
    ensure_fallbacks(); ask_page(); routes=collect_routes(); write_knowledge(routes); injected=inject(); routes=collect_routes(); write_knowledge(routes); patch_readme(); docs_and_reports(routes,injected); (PUBLIC/'.nojekyll').write_text('',encoding='utf-8'); print(json.dumps({'status':'passed','routes':len(routes),'pagesInjected':injected},indent=2))
if __name__=='__main__': main()
