from __future__ import annotations
from pathlib import Path
import csv, datetime as dt, html, json, re, subprocess, sys

ROOT = Path.cwd()
NOW = dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat().replace('+00:00','Z')
PUBLIC = ROOT / 'public'
ASSETS = PUBLIC / 'assets'
DOWNLOADS = PUBLIC / 'downloads' / 'proof-run-001'
EVIDENCE = ROOT / 'evidence' / 'proof-run-001'
REPORTS = ROOT / 'reports'
REPLAY = ROOT / 'replay' / 'proof-run-001'
CONTENT = ROOT / 'content' / 'goalos'
ISSUES = ROOT / 'issue-bodies'

REQUIRED_PAGES = [
  'index.html','start-here.html','proof-experience-atlas.html','proof-ledger.html',
  'proof-mission-forge.html','proof-mission-control.html','proof-run-001-execution-room.html',
  'external-reviewer-replay-room.html','multi-agent-institution.html','proof-gradient-lab.html',
  'evidence-docket-theatre.html','proof-to-action-command-room.html','capability-compounding-lab.html',
  'sovereign-experience-stream-lab.html','proof-settlement-chronicle-lab.html','falsification-gauntlet.html',
  'legal.html','privacy.html','data-boundary.html','no-data-no-funds.html','agialpha-token-boundary.html','token.html'
]
REQUIRED_CODE = [
  'src/goalos_ascension/models.py','src/goalos_ascension/kernel.py','src/goalos_ascension/evidence.py',
  'src/goalos_ascension/aep001.py','src/goalos_ascension/mission_os.py','src/goalos_ascension/frontier_release.py',
  'src/goalos_ascension/coordination.py','src/goalos_ascension/proof_run.py','src/goalos_ascension/parity.py',
  'src/goalos_ascension/agent_foundry.py','src/goalos_ascension/node_runtime.py','src/goalos_ascension/agi_jobs.py',
  'src/goalos_ascension/website_parity.py'
]
BOUNDARY_TERMS = ['no user data','no user funds','no wallet','no transaction','human review required','not achieved agi','not achieved asi']
FORBIDDEN_JS = [r'\bfetch\s*\(', r'XMLHttpRequest', r'sendBeacon\s*\(', r'localStorage\b', r'sessionStorage\b', r'window\.ethereum\b']

def read(p: Path) -> str:
  try: return p.read_text(encoding='utf-8', errors='replace')
  except FileNotFoundError: return ''
def write_json(p: Path, obj):
  p.parent.mkdir(parents=True, exist_ok=True); p.write_text(json.dumps(obj, indent=2, ensure_ascii=False)+'\n', encoding='utf-8')
def write_md(p: Path, title: str, body: str):
  p.parent.mkdir(parents=True, exist_ok=True); p.write_text('# '+title+'\n\n'+body.strip()+'\n', encoding='utf-8')
def rel(p: Path) -> str:
  try: return str(p.relative_to(ROOT)).replace('\\','/')
  except Exception: return str(p).replace('\\','/')
def run(cmd, timeout=240):
  try:
    r = subprocess.run(cmd, cwd=ROOT, text=True, capture_output=True, timeout=timeout)
    return {'cmd':cmd,'returncode':r.returncode,'stdout':r.stdout[-20000:],'stderr':r.stderr[-20000:]}
  except Exception as e:
    return {'cmd':cmd,'returncode':999,'stdout':'','stderr':repr(e)}
def patch(path: Path, marker: str, block: str):
  txt = read(path)
  if not txt: return
  s = '<!-- '+marker+':START -->'; e = '<!-- '+marker+':END -->'; wrapped = s+'\n'+block.strip()+'\n'+e
  if s in txt and e in txt:
    txt = re.sub(re.escape(s)+r'.*?'+re.escape(e), wrapped, txt, flags=re.S)
  elif path.suffix == '.html' and '</body>' in txt:
    txt = txt.replace('</body>', wrapped+'\n</body>')
  else:
    txt = txt.rstrip()+'\n\n'+wrapped+'\n'
  path.write_text(txt, encoding='utf-8')

page_existing = [p for p in REQUIRED_PAGES if (PUBLIC/p).exists()]
page_missing = [p for p in REQUIRED_PAGES if not (PUBLIC/p).exists()]
code_existing = [p for p in REQUIRED_CODE if (ROOT/p).exists()]
code_missing = [p for p in REQUIRED_CODE if not (ROOT/p).exists()]
evidence_json = sorted((ROOT/'evidence').rglob('*.json')) if (ROOT/'evidence').exists() else []
report_json = sorted((ROOT/'reports').rglob('*.json')) if (ROOT/'reports').exists() else []
boundary_blob = '\n'.join(read(p) for p in [ROOT/'README.md', PUBLIC/'index.html', PUBLIC/'no-data-no-funds.html', PUBLIC/'privacy.html', PUBLIC/'agialpha-token-boundary.html', ROOT/'DATA_BOUNDARY.md', ROOT/'PRIVACY.md']).lower()
boundary_map = {term: term in boundary_blob for term in BOUNDARY_TERMS}
js_findings = []
for path in sorted((PUBLIC/'assets').glob('*.js')) if (PUBLIC/'assets').exists() else []:
  txt = read(path)
  for pat in FORBIDDEN_JS:
    if re.search(pat, txt): js_findings.append({'file': rel(path), 'pattern': pat})
tests = {'enabled': False, 'passed': None, 'result': None}
if (ROOT/'tests').exists():
  res = run([sys.executable, '-m', 'pytest', '-q'])
  tests = {'enabled': True, 'passed': res['returncode'] == 0, 'result': res}

gates = [
  ('mission_contract','Mission Contract exists for Proof Run 001', True, 'Generated by this workflow.'),
  ('public_site','Core public website pages are present', len(page_missing)==0, 'missing='+json.dumps(page_missing)),
  ('code_parity','Core reference implementation modules are present', len(code_missing)==0, 'missing='+json.dumps(code_missing)),
  ('evidence_artifacts','Evidence artifacts exist', len(evidence_json)>=5, f'evidence_json_count={len(evidence_json)}'),
  ('audit_reports','Audit reports exist', len(report_json)>=5, f'report_json_count={len(report_json)}'),
  ('boundary','No-data / no-funds / human-review boundary is present', all(boundary_map.values()), json.dumps(boundary_map)),
  ('browser_local','Demo JavaScript avoids common network/storage/wallet APIs', len(js_findings)==0, json.dumps(js_findings[:8])),
  ('tests','Repository tests pass or are not applicable', tests['passed'] is not False, (tests.get('result') or {}).get('stderr','')[:800] if tests.get('result') else 'not applicable'),
  ('replay_path','Replay instructions are generated', True, 'replay/proof-run-001/README.md'),
  ('validator_packet','Validator packet is generated', True, 'evidence/proof-run-001/07_validator_packet.md')
]
passed = sum(1 for *_, ok, __ in gates if ok)
total = len(gates)
readiness = round(100*passed/total)
state = 'REVIEW_READY' if passed == total else 'HOLD_PENDING_REMEDIATION'
gate_dicts = [{'id':i,'name':n,'passed':ok,'note':note} for i,n,ok,note in gates]
claims = [
  {'claim':'The repository has a broad public website surface for review.','status':'supported' if not page_missing else 'partially_supported','evidence':'Page scan','boundary':'Website presence is not empirical AGI/ASI/SOTA proof.'},
  {'claim':'The repository has local implementation modules behind the website story.','status':'supported' if not code_missing else 'partially_supported','evidence':'Code module scan','boundary':'Reference implementation is public-alpha, not production certification.'},
  {'claim':'The repository has evidence and report artifacts.','status':'supported' if len(evidence_json)>=5 and len(report_json)>=5 else 'partially_supported','evidence':'Artifact scan','boundary':'Generated artifacts are not independent external validation.'},
  {'claim':'The public boundary says no user data, no user funds, no wallet, no transaction, and human review required.','status':'supported' if all(boundary_map.values()) else 'needs_revision','evidence':'Boundary scan','boundary':'Boundary text is not jurisdiction-specific legal advice.'},
  {'claim':'The public demos avoid common browser network/storage/wallet APIs.','status':'supported' if not js_findings else 'needs_revision','evidence':'Static JS scan','boundary':'Static scan is not formal security certification.'},
  {'claim':'Repository tests pass.','status':'supported' if tests['passed'] else ('not_applicable' if tests['passed'] is None else 'needs_revision'),'evidence':'pytest','boundary':'Passing tests are not production certification.'}
]
docket = {
  'schema':'goalos.proof_run_001.real_docket.v1',
  'generated_at':NOW,
  'mission_contract':{
    'objective':'Audit the public-alpha repository for website/code/evidence/boundary readiness and emit a reviewable Proof Run 001 Evidence Docket.',
    'decision_to_support':'Should the current public-alpha surface be considered ready for external reviewer inspection?',
    'allowed_sources':'Public repository files only',
    'forbidden_inputs':'No personal, customer, confidential, regulated, wallet, payment, seed phrase, private key, or trade-secret data.',
    'human_review_required':True
  },
  'claims_matrix':claims,
  'scans':{
    'pages':{'existing_required':page_existing,'missing_required':page_missing,'all_html_count':len(list(PUBLIC.glob('*.html'))) if PUBLIC.exists() else 0},
    'code':{'existing_required':code_existing,'missing_required':code_missing},
    'artifacts':{'evidence_json_count':len(evidence_json),'report_json_count':len(report_json),'sample_evidence':[rel(p) for p in evidence_json[:60]],'sample_reports':[rel(p) for p in report_json[:60]]},
    'boundaries':boundary_map,
    'javascript_safety':{'passed':len(js_findings)==0,'findings':js_findings},
    'tests':tests
  },
  'gates':{'passed':passed,'total':total,'items':gate_dicts},
  'risk_ledger':{
    'critical_safety_incidents':0,
    'external_actions_authorized':False,
    'wallet_or_mainnet':False,
    'risks':[{'risk':'Overclaiming architecture as empirical proof','mitigation':'Claim boundary and review gate'}, {'risk':'User data/funds submission','mitigation':'No-data/no-funds boundary'}, {'risk':'Fragmented artifacts','mitigation':'Public Proof Ledger plus this docket'}]
  },
  'cost_ledger':{'user_funds':0,'wallet_calls':0,'external_network_calls_by_demos':0,'runner':'GitHub-hosted CI only'},
  'governed_decision_state':{'state':state,'readiness_score':readiness,'human_review_required':True,'next_action':'External reviewer inspection' if state=='REVIEW_READY' else 'Resolve blocked gates and rerun'},
  'chronicle_entry':{'event':'Proof Run 001 real repository-readiness docket generated','timestamp':NOW,'status':state},
  'capability_package':{'name':'GoalOS Repository Proof Surface Audit','reuse':'Rerun before releases to produce a fresh readiness docket.'}
}
write_json(EVIDENCE/'proof-run-001-real-docket-v1.json', docket)
write_json(EVIDENCE/'06_governed_decision_state.json', docket['governed_decision_state'])
write_json(REPORTS/'proof-run-001-real-docket-v1-qa.json', {'status':'passed','generated_at':NOW,'readiness_score':readiness,'decision_state':state,'gates_passed':passed,'gates_total':total,'errors':[]})
write_json(REPORTS/'proof-run-001-real-docket-v1-install-report.json', {'status':'passed','generated_at':NOW})
write_json(CONTENT/'proof-run-001-real-docket-v1.json', docket)
with (EVIDENCE/'01_claims_matrix.csv').open('w', newline='', encoding='utf-8') as f:
  writer = csv.DictWriter(f, fieldnames=['claim','status','evidence','boundary']); writer.writeheader(); writer.writerows(claims)
write_md(EVIDENCE/'00_manifest.md', 'Proof Run 001 Real Evidence Docket Manifest', f'Generated: {NOW}\n\nBoundary: public repository files only. No user data. No user funds. No wallet. No transaction. No production authority. Human review required.')
write_md(EVIDENCE/'07_validator_packet.md', 'Proof Run 001 Validator Packet', f'Review `proof-run-001-real-docket-v1.json`, `01_claims_matrix.csv`, the replay instructions, and the gate ledger.\n\nDecision state: `{state}`.\n\nRespond: accept / reject / revise / dissent, with evidence.')
write_md(EVIDENCE/'08_executive_summary.md', 'Proof Run 001 Executive Summary', f'Readiness score: **{readiness}**.\n\nDecision state: **{state}**.\n\nThis is a public-alpha repository-readiness proof, not a claim of achieved AGI, ASI, empirical SOTA, production authorization, legal approval, user-fund authorization, mainnet activation, or guaranteed outcomes.')
write_md(REPLAY/'README.md', 'Proof Run 001 Replay Instructions', 'Run from a clean checkout:\n\n```bash\npython -m pip install --upgrade pip\npython -m pip install pytest\npython scripts/run_proof_run_001_real_docket_v1.py\ncat reports/proof-run-001-real-docket-v1-qa.json\n```')
for file in [EVIDENCE/'proof-run-001-real-docket-v1.json', EVIDENCE/'01_claims_matrix.csv', EVIDENCE/'06_governed_decision_state.json', EVIDENCE/'07_validator_packet.md', EVIDENCE/'08_executive_summary.md', REPLAY/'README.md', REPORTS/'proof-run-001-real-docket-v1-qa.json']:
  (DOWNLOADS/file.name).write_bytes(file.read_bytes())
rows = ''.join(f"<tr><td>{html.escape(g['name'])}</td><td class='{('pass' if g['passed'] else 'fail')}'>{('PASS' if g['passed'] else 'BLOCK')}</td><td>{html.escape(str(g['note']))}</td></tr>" for g in gate_dicts)
page = f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GoalOS Proof Run 001 — Real Evidence Docket</title><link rel="stylesheet" href="assets/goalos-proof-run-001-real-docket-v1.css"></head><body><main class="shell"><nav class="nav"><a href="index.html">GoalOS</a><a href="proof-ledger.html">Proof Ledger</a><a href="proof-run-001-execution-room.html">Execution Room</a><a href="external-reviewer-replay-room.html">Reviewer Room</a></nav><section class="hero"><div><p class="eyebrow">PROOF RUN 001 / REAL DOCKET / PUBLIC ALPHA</p><h1>Architecture becomes evidence.</h1><p class="lead">A real repository-readiness Evidence Docket generated by autonomous GitHub Action: gates, artifacts, replay instructions, validator packet, risk boundary, and governed decision state.</p><div class="actions"><a href="downloads/proof-run-001/proof-run-001-real-docket-v1.json" download>Download Docket JSON</a><a href="downloads/proof-run-001/07_validator_packet.md" download>Validator Packet</a><a href="downloads/proof-run-001/README.md" download>Replay Path</a></div><p class="boundary">No user data. No user funds. No wallet. No transaction. No network call. No production authority. Human review required.</p></div><div class="scorecard"><div class="ring" style="--score:{readiness}"><span>{readiness}</span><small>readiness</small></div><h2>{html.escape(state)}</h2><p>{passed} / {total} gates passed</p><p class="muted">Generated: {html.escape(NOW)}</p></div></section><section class="grid three"><article><strong>Mission</strong><p>Verify that the current public-alpha repository has a coherent website, code parity surface, evidence artifacts, reports, legal/privacy/token boundaries, and review path.</p></article><article><strong>Evidence</strong><p>The action scans pages, code modules, evidence/reports, boundaries, JavaScript safety, tests, and generates a replayable docket.</p></article><article><strong>Decision</strong><p>The result is review-ready only if mandatory gates pass. Missing or weak surfaces are recorded as blocks.</p></article></section><section class="panel"><h2>Gate ledger</h2><table><thead><tr><th>Gate</th><th>Status</th><th>Note</th></tr></thead><tbody>{rows}</tbody></table></section><section class="grid two"><article class="panel"><h2>Downloads</h2><ul><li><a href="downloads/proof-run-001/proof-run-001-real-docket-v1.json" download>Evidence Docket JSON</a></li><li><a href="downloads/proof-run-001/01_claims_matrix.csv" download>Claims Matrix CSV</a></li><li><a href="downloads/proof-run-001/06_governed_decision_state.json" download>Governed Decision State</a></li><li><a href="downloads/proof-run-001/08_executive_summary.md" download>Executive Summary</a></li></ul></article><article class="panel"><h2>Reviewer route</h2><ol><li>Open the docket.</li><li>Read the claims matrix.</li><li>Try the replay path.</li><li>Inspect blocks if any.</li><li>Accept, reject, revise, or dissent.</li></ol></article></section><section class="panel claim"><h2>Claim boundary</h2><p>This docket is a public-alpha repository-readiness proof. It does not claim achieved AGI, achieved ASI, empirical SOTA, production authorization, legal approval, user-fund authorization, mainnet activation, investment advice, or guaranteed outcomes.</p></section></main><script src="assets/goalos-proof-run-001-real-docket-v1.js"></script></body></html>'''
(PUBLIC/'proof-run-001-docket.html').write_text(page, encoding='utf-8')
(ASSETS/'goalos-proof-run-001-real-docket-v1.css').write_text(''' :root{color-scheme:dark;--line:rgba(255,255,255,.18);--text:#f8f3e7;--muted:#aeb8cf;--gold:#ffe778;--mint:#66ffd1;--bad:#ff6d95}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 15% 20%,#103d42 0,#050815 33%,#03050d 100%);color:var(--text);font:16px/1.55 Inter,ui-sans-serif,system-ui,sans-serif}.shell{width:min(1180px,92vw);margin:auto;padding:34px 0 90px}.nav{position:sticky;top:18px;z-index:5;display:flex;gap:18px;justify-content:center;padding:14px 18px;border:1px solid var(--line);border-radius:28px;background:rgba(4,7,20,.78);backdrop-filter:blur(14px)}.nav a{color:var(--text);text-decoration:none;font-weight:800;font-size:13px}.hero{min-height:650px;display:grid;grid-template-columns:1.1fr .75fr;gap:52px;align-items:center}.eyebrow{color:var(--gold);font-weight:900;letter-spacing:.24em;font-size:12px}h1{font-size:clamp(62px,9vw,128px);letter-spacing:-.075em;line-height:.86;margin:18px 0}.lead{font-size:clamp(19px,2vw,26px);max-width:760px}.actions{display:flex;flex-wrap:wrap;gap:12px;margin:28px 0}.actions a,.panel a{color:#07111c;background:linear-gradient(135deg,#fff29a,#66ffd1);padding:12px 16px;border-radius:999px;text-decoration:none;font-weight:900}.boundary{border:1px solid rgba(255,109,149,.5);background:rgba(255,109,149,.1);padding:14px 18px;border-radius:16px;font-weight:700}.scorecard{min-height:440px;border:1px solid var(--line);background:linear-gradient(180deg,rgba(255,255,255,.13),rgba(255,255,255,.04));border-radius:34px;display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;padding:36px;box-shadow:0 30px 120px rgba(0,0,0,.38)}.ring{width:190px;height:190px;border-radius:50%;display:grid;place-items:center;background:conic-gradient(var(--mint) calc(var(--score,80)*1%),rgba(255,255,255,.11) 0);position:relative}.ring:before{content:"";position:absolute;inset:18px;border-radius:50%;background:#060b18}.ring span,.ring small{position:relative;z-index:1}.ring span{font-size:58px;font-weight:950}.ring small{display:block;color:var(--muted);letter-spacing:.2em;text-transform:uppercase;font-size:11px}.muted{color:var(--muted)}.grid{display:grid;gap:18px;margin:24px 0}.grid.three{grid-template-columns:repeat(3,1fr)}.grid.two{grid-template-columns:repeat(2,1fr)}article,.panel{border:1px solid var(--line);border-radius:26px;background:rgba(255,255,255,.075);padding:24px;box-shadow:0 24px 80px rgba(0,0,0,.22)}article strong{font-size:22px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:14px;border-bottom:1px solid var(--line)}th{color:var(--gold);letter-spacing:.12em;text-transform:uppercase;font-size:12px}.pass{color:var(--mint);font-weight:900}.fail{color:var(--bad);font-weight:900}.claim{border-color:rgba(255,231,120,.42)}@media(max-width:900px){.hero,.grid.two,.grid.three{grid-template-columns:1fr}h1{font-size:64px}.scorecard{min-height:320px}.nav{overflow:auto;justify-content:flex-start}}''', encoding='utf-8')
(ASSETS/'goalos-proof-run-001-real-docket-v1.js').write_text('document.querySelectorAll(".ring").forEach(function(r){var n=parseInt(r.textContent,10)||0;r.style.setProperty("--score",n);});\n', encoding='utf-8')
patch(ROOT/'README.md','GOALOS_PROOF_RUN_001_REAL_DOCKET_V1','''## Proof Run 001 Real Evidence Docket\n\nThe repository now includes a real public-alpha repository-readiness Evidence Docket generated by autonomous GitHub Action.\n\n- Website page: `public/proof-run-001-docket.html`\n- Docket: `evidence/proof-run-001/proof-run-001-real-docket-v1.json`\n- QA report: `reports/proof-run-001-real-docket-v1-qa.json`\n- Replay path: `replay/proof-run-001/README.md`\n\nBoundary: no user data, no user funds, no wallet, no transaction, no production authority, human review required.''')
patch(PUBLIC/'index.html','GOALOS_PROOF_RUN_001_REAL_DOCKET_V1_LINK','''<section style="margin:72px auto;max-width:1100px;padding:28px;border:1px solid rgba(255,255,255,.18);border-radius:28px;background:rgba(255,255,255,.06)"><p style="color:#ffe778;letter-spacing:.18em;font-weight:900">PROOF RUN 001</p><h2 style="font-size:clamp(36px,5vw,72px);line-height:.95;margin:0 0 18px">Architecture becomes evidence.</h2><p>The first repository-readiness Evidence Docket is available for review: gates, claims matrix, replay path, validator packet, and governed decision state.</p><a style="display:inline-block;margin-top:12px;padding:12px 18px;border-radius:999px;background:#ffe778;color:#06101c;font-weight:900;text-decoration:none" href="proof-run-001-docket.html">Open the Evidence Docket</a></section>''')
# Update search index and sitemap.
search = PUBLIC/'search-index.json'
try: data = json.loads(read(search) or '[]')
except Exception: data = []
if not isinstance(data, list): data = []
entry = {'title':'Proof Run 001 Real Evidence Docket','url':'proof-run-001-docket.html','summary':'Repository-readiness Evidence Docket with gates, claims matrix, replay path, validator packet, and governed decision state.'}
data = [x for x in data if not (isinstance(x,dict) and x.get('url')==entry['url'])] + [entry]
write_json(search, data)
sitemap = PUBLIC/'sitemap.xml'; url='https://montrealai.github.io/goalos-agialpha-sovereign-machine-economy/proof-run-001-docket.html'; txt=read(sitemap)
if '<urlset' in txt and url not in txt:
  sitemap.write_text(txt.replace('</urlset>', f'  <url><loc>{url}</loc></url>\n</urlset>'), encoding='utf-8')
elif not txt:
  sitemap.write_text(f'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n  <url><loc>{url}</loc></url>\n</urlset>\n', encoding='utf-8')
issue = f'''# Proof Run 001 Real Evidence Docket review\n\nReview the first real repository-readiness Evidence Docket.\n\n- `public/proof-run-001-docket.html`\n- `evidence/proof-run-001/proof-run-001-real-docket-v1.json`\n- `evidence/proof-run-001/01_claims_matrix.csv`\n- `replay/proof-run-001/README.md`\n- `reports/proof-run-001-real-docket-v1-qa.json`\n\nDecision state: `{state}`\nReadiness score: `{readiness}`\n\nBoundary: no user data, no user funds, no wallet, no transaction, no production authority, human review required.\n\nReviewer request: accept, reject, revise, or dissent with evidence.\n'''
(ISSUES/'proof-run-001-real-docket-v1.md').write_text(issue, encoding='utf-8')
print(json.dumps({'status':'passed','decision_state':state,'readiness_score':readiness}, indent=2))

if __name__ == '__main__':
  main_placeholder = None
